### ISSUE TITLE
Failed to replace cfg files

### ISSUE THREAD

**Issue by bizbasz** [iabarca/lawena-recording-tool#101]
hey, i want to record demos but i cant cuz lawena (4.1.16) said "Failed to replace cfg files" and i need to restart my computer 3-4 times for it is work. And i always restart explorer.exe but is not working. 
Thanks for read this.

**Comment by quanticc** [comment]
There is a problem when copying Lawena files to your cfg folder. I need more info to make sure what kind of problem this is.

Please attach your Lawena log file here (as a .txt) or paste it into http://hastebin.com/

File is located in the ``lawena`` folder and it's called `lawena.0.0.log`

**Comment by bizbasz** [comment]
I dont found lawena.0.0.log but i can send the log from the client https://hastebin.com/yeteyusape.css

**Comment by bizbasz** [comment]
And this is a link from my lawena folder: http://prntscr.com/gwhn84

**Comment by quanticc** [comment]
You need to manually sort out the files as Lawena is trying to move files from "cfg" to "lwrtcfg", and that last folder already exists, stopping the process.
