### ISSUE TITLE
Hud bugs..

### ISSUE THREAD

**Issue by eddie-englund** [iabarca/lawena-recording-tool#104]
Hi! I've got an issue where the console is in half and I cannot type nor do anything in the game even when using bindings!!!

![lawena](https://user-images.githubusercontent.com/16852656/32408599-1e9846a8-c19b-11e7-9d58-70f13f3a4cfe.PNG)

**Comment by quanticc** [comment]
Hi. I released a new version fixing this issue, but it's only working if you freshly download it, since the automatic updater has issues with deleting files.

Get this one: https://github.com/quanticc/lawena-recording-tool/releases/download/4.1.17/lawena-stable-4.1.17.zip

Sorry for the trouble.
