### ISSUE TITLE
Halloween request.

### ISSUE THREAD

**Issue by rky1** [iabarca/lawena-recording-tool#105]
When recording during a the full moon mode it of course affects your demos and has horrible ghost noises and souls flying about through the entire thing. I can't figure out how to disable them.

I found the origin of the noise in tf2_sound_misc_dir -> sound/player/souls_receive

Help would be much appreciated, thanks.

**Comment by quanticc** [comment]
The files are these:

sound/player/souls_receive1.wav
sound/player/souls_receive2.wav
sound/player/souls_receive3.wav

Lawena uses "blank" mp3/wav files to replace sounds. You can supply your own custom folder inside Lawena custom folder to be copied to the game when you launch it. It can be a folder or a vpk file.

I made a quick example that might work for your case (zip file, try extracting it to custom folder)
[no_souls_receive.zip](https://github.com/quanticc/lawena-recording-tool/files/1448727/no_souls_receive.zip)

**Comment by rky1** [comment]
Thank you for your very fast response. Do you know how one can remove the ghost/soul trails that fly about towards players after kills?

There is also a sound as the souls enter the body. Sounds like a sucking noise lol

**Comment by quanticc** [comment]
I don't know about the particular sounds, sorry. But the process of removing them is the same.
