### ISSUE TITLE
Issue with recording jigglebones

### ISSUE THREAD

**Issue by Tesla6502** [iabarca/lawena-recording-tool#109]
Hi there, I'm having some issues with enabling jigglebones while lawena is recording. It seems that, no matter what framerate I set the cl_jiggle_bone_framerate_cutoff to, when lawena is recording frames no jigglebones are enabled. There aren't any issues with jigglebones when I'm not recording. Some help would be appreciated!

**Comment by quanticc** [comment]
Have you tried something like this?
```
cl_jiggle_bone_framerate_cutoff 0
alias cl_jiggle_bone_framerate_cutoff ""
```

**Comment by Tesla6502** [comment]
Nope, doesn't do the trick.
