### ISSUE TITLE
Allow repeat recording of player perspectives

### ISSUE THREAD

**Issue by joekiller** [iabarca/lawena-recording-tool#111]
One thing I'd like to attempt to figure out is how to make multiple renderings of the same video over and over from each player's perspective. 

It appears that demo tick segments all run simultaneously even if they are ordered in the VDM file which was a little contrary to what I expected.

I'm imagining a series of aliases that would change to allow multiple actions to occur on the same tick but only be activated after the expected action happened.

IE at tick 3 there are three records. Each runs a different alias command:

Initially

segment 3 has: alias1= record segment; alias alias1 noop;
segment 3 has: alias2 = noop
segment 3 has: alias3 = noop
segment 4 has: exec playerswitch
segment N has: alias alias2 = record segment; alias alias2 noop;

next iteration all three fire but only 2 is active so

alias1=noop
alias2 = record segment; alias alias2 noop;
alias3 = noop

Does this make sense?

**Comment by quanticc** [comment]
Yes, if you are able to "rewind" or start the demo over, it would work.

I think it would resemble how the recording process rotates between different files each time you press P.
