### ISSUE TITLE
Lawena Movie Folder Issue

### ISSUE THREAD

**Issue by dablobman** [iabarca/lawena-recording-tool#112]
I set my movie folder, but Lawena keeps recording the movie into my /tf folder for some reason. Any explanation for this?

**Comment by quanticc** [comment]
To what folder are you trying to set it?

I introduced a workaround for a TF2 issue with recording folders, where only folders below the tf dir work. Depending on your answer this might a bug with the workaround.

At any case, you would only be able to record frames if your movie path is under tf folder (or at least in the same drive if not using symlinks)

See the thread after https://github.com/quanticc/lawena-recording-tool/issues/82#issuecomment-345544117 to get more context.
