### ISSUE TITLE
Can't run launcher

### ISSUE THREAD

**Issue by basicwhiteboy** [iabarca/lawena-recording-tool#116]
So, I tried to open lawena, but it gives me the message 
"The application has failed to launch due to a missing resource: https://dl.dropboxusercontent.com/u/74380/lwrt/v4.1.x/stable/latest/getdown.txt

please visit
for details on how to handle such problems."
Anyone know what to do?

**Comment by quanticc** [comment]
Please download most recent release. I have switched to a different provider a year ago.
