### ISSUE TITLE
Custom recording hud recently stopped functioning.

### ISSUE THREAD

**Issue by krollic** [iabarca/lawena-recording-tool#118]
For a long time now I've been using this recording hud which is basically kill-streaks only but has white damage numbers. https://dl.dropboxusercontent.com/content_link_zip/PR83jmyvxcI952Lj1Iy5UlCK6SOPNfZtS5dCNV4T2jhco72xrTgaNz66XndpV72H/file?_download_id=0118602510064738117581194393372668310883680382097351720236594452791&_notify_domain=www.dropbox.com&dl=1

This is what it usually looked like: https://i.imgur.com/AwYisXu.png
And now it looks like this: https://imgur.com/UzKnO2d

I'm not really sure how do go about repairing this so I figured I'd ask for your help if possible, please.
Thank you for your great tool :]

**Comment by quanticc** [comment]
These were recently added to the game:
```
hud_combattext_red [0-255]
hud_combattext_green [0-255]
hud_combattext_blue [0-255]
```

Maybe this is what you're looking for?
