### ISSUE TITLE
Failed to replace custom files

### ISSUE THREAD

**Issue by Gengartf2** [iabarca/lawena-recording-tool#21]
Okay well forgive me if this is just me being stupid and screwing up the installation or something but when I click to start TF2 it just says fails to replace custom files, the registry thing comes up and I hit okay and then nothing. I'm like just trying to get into the whole recording thing so again forgive me if the solution is obvious but if someone could just point me in the right direction I'd really appreciate it. Thanks.

**Comment by zacice** [comment]
I have the same problem but I restarted steam and it didnt do a thing. I launched lawena by opening gradlew then click Team Fortress 2 and make a vdm file click launch game and every time it says the error failed load custom files.

**Comment by iabarca** [comment]
@zacice  If you use gradlew you have to run it as administrator. I recommend that you try to use the lawena.exe file since that already does that for you. Also make sure you haven't set your folders to read-only.

If this doesn't fix your problem then I'm afraid this is not directly related to the issue you posted in, can you paste the log file called ``lawena.0.0.log`` to http://pastebin.com/ and send me the link?

**Comment by zacice** [comment]
Yea my folders when I go to proprities they have read only not checked but coloured in and when I take that off it comes back, also the run as administrator did not work and running the lawena.exe 4.1.6 stable did not work.

I think this is my lawena logs: http://pastebin.com/8B3U7Dqv

**Comment by iabarca** [comment]
There is something preventing the folder move, maybe a permission or read-only folder problem.

To test if something inside your custom folder is causing this, can you make a backup of your custom folder, delete all contents in ``tf/custom`` folder and then disable the read-only property? Also please use 4.1.6 stable run from the .exe file only.

**Comment by zacice** [comment]
Ok now I think I did not install lawena right. Do you have to do anything with the folders in lawena? Because I have no clue.

**Comment by iabarca** [comment]
Not really, download the lawena-stable-4.1.6.zip from release page [[Link here](https://github.com/iabarca/lawena-recording-tool/releases/download/4.1.6/lawena-stable-4.1.6.zip)]

Extract to a clean folder and execute lawena.exe

**Comment by zacice** [comment]
Ok I guess for some reason it works now

**Comment by iabarca** [comment]
Thanks for letting me know. In case something different breaks, feel free to tell me in the [Chat](https://gitter.im/iabarca/lawena-recording-tool) or create a new issue if it's needed.

**Comment by zacice** [comment]
Nvm Now it says failed to replace cfg files :/

**Comment by iabarca** [comment]
Come to the chat, it's better
