### ISSUE TITLE
Issue When Recording Starts

### ISSUE THREAD

**Issue by DuckieMomo** [iabarca/lawena-recording-tool#27]
Hello all, 

  Today I decided to make some nice TF2 gameplay videos for the first time, but the thing is I have followed everything I need to do before recording; When I press "P" to start recording, it begins, and my character just freezes in one place till I stop the recording. What seems to be the issue? Any help will be thankful!

**Comment by iabarca** [comment]
Replying for someone else that might encounter the same issue: Some keybinds you might have can override Lawena's P key bind that's assigned to the command ``startrecording``. You can enter that command to achieve the same result. Also you can type this into console:

``bind P startrecording`` after your demo starts (which is the point where it got overridden in the first place)
