### ISSUE TITLE
Team Fortress 2 crashing on playing demos

### ISSUE THREAD

**Issue by Teataim** [iabarca/lawena-recording-tool#52]
Whenever I start Team Fortress 2 using lawena and play any demo, it crashes out of the game relatively soon, but it still starts the demo normally.
It appears the crash happens when I first deal damage or the first time when it would make a hitsound.
I have a custom hitsound that changes its pitch depending on how much damage I deal and I use ToonHUD and have customized (bigger) damage numbers.
I have tried having both hud and hitsound turned on, but TF2 still crashed at the exact same point.
Is there anything I could try?

-Teatime

**Comment by iabarca** [comment]
I've seen this problem but never crashing on the exact same place, only randomly. Anyway this is most likely related to the maxquality configs in the ``cfg/recording.cfg`` file, especially if you can play it normally without using Lawena.

I'm not sure what command is triggering the crashes, so I'd advise you to use a different graphical config. Like this:

https://gist.github.com/iabarca/382ab3a7ad0785e49a02

Download that ``recording.cfg`` and replace the file in the ``cfg`` folder. Create a copy of the original file if you wish so you don't lose it.

If you could test that config and let me know of your results, it would be very helpful. Thanks for reporting this issue.

**Comment by Teataim** [comment]
I did that, it didn't help and actually changed nothing.
Apparently the moment it crashed just happened to be the moment that I dealt damage to someone in some demos, so that's not the actual reason.
The crash also often happens at around 1000-2000 ticks in.

**Comment by iabarca** [comment]
I still find weird that crashes occur on the same spot. I assume this only happens when using Lawena, right? Because Lawena is just swapping files and configs for you.

There are two things that can be tried:
1. Try typing ``mat_queue_mode -1`` in console. This is a multithreading setting.
2. Can you upload a demo of yours to reproduce it in my machine? And to further test without bothering you much.

Thanks

**Comment by Teataim** [comment]
Yes, it only occurs when I use lawena, sorry I did not mention that yet.
mat_queue_mode -1 does not change anything, still crashes at the same spot.
You might want to back your cfg folder up before playing my demo, there have been problems with people having my crosshair switcher (broesel's crosshair switcher) after playing one of my POV demos.
Otherwise, there you go:
https://dl.dropboxusercontent.com/u/132809724/20150127_2052_koth_viaduct_pro5_red_ablu.zip
Also feel free to bother me as much as you want, you can add me on steam if you want (http://steamcommunity.com/id/timefortea).
Thank you for your help so far.

-Teatime

**Comment by iabarca** [comment]
I could not reproduce the crash during playback of that demo when viewed normally (no tick skipping). I'm convinced it's related to the graphical settings but at this point I can't give you a proper solution.

Sorry I can't help you much further.

**Comment by Kaneco** [comment]
Have you tried disabling the custom hud for recording and use one of the ones provided by lawena? It might be a problem related to that.

**Comment by scoliono** [comment]
Since this hasn't been closed yet, I'd like to add to this discussion. I am having the same problem, and the demo crashes at tick 65262 every time I play it, whether I'm using mat_queue_mode -2 or 0. I don't remember this problem ever happening in the past with much longer demos (but I also don't remember if I had used Lawena back then). The demo plays/tick-skips fine without Lawena. Also, I use broeselhud when recording but use the default on minimum mode during regular play.

**Comment by iabarca** [comment]
I'm still not sure it's unrelated to other threading/graphic convars. Have you also tested changing the ``cfg/recording.cfg`` file with [this one](https://gist.github.com/iabarca/382ab3a7ad0785e49a02)? That is a modified cfg from Source Recording Tool.

Also if you could, please check if you crash when using no ``recording.cfg`` file at all (default settings).

**Comment by scoliono** [comment]
TF2 still crashes with your modified config and no recording.cfg at all.

**Comment by iabarca** [comment]
Thanks for testing them, I'll continue to look for the cause.

**Comment by TremFortyTwo** [comment]
Hey,

I had a similar problem, and actually stumbled across this page trying to find a solution. Often mat_queue_mode 0 and -1 (and 2 when playing normally) are suggested, none of them working. However, after trying a gazillion different things, it seems that simply putting mat_queue_mode to 1 fixed it for me; I just finished rendering 2 clips on a demo that used to crash at the same point all the time before.
Don't know if this will solve it for you as well, but hopefully it'll help some at least :>

**Comment by Cod-ZA** [comment]
When I launch TF2 through Lawena and try to play a demo, TF2 freezes and the demo doesn't play.

**Comment by iabarca** [comment]
@Cod-ZA Is it a particular demo or all of them? Can you check with ``mat_queue_mode 1``? The main difference between playing a demo with and without the tool is the ``recording.cfg`` config file.

``mat_queue_mode`` is one of the settings there, along many others to push maximum graphic settings. You could also try temporarily renaming the ``recording.cfg`` to use TF2 default settings.

**Comment by Cod-ZA** [comment]
All of them. Mat_queue_mode 1 fixes the problem. Thanks
