### ISSUE TITLE
TF2 Crashes after clicking "load" on demoui

### ISSUE THREAD

**Issue by Bearnaut** [iabarca/lawena-recording-tool#58]
I don't know for what reason but starting from 2 days ago, after starting tf2 from Lawena, loading demos through any of the DemoUIs would cause tf2 to crash, not after loading the demo but exactly as you click on the load button.
This problem doesn't ocurr when loading from the console. On a side note, is it normal for demos obtained from servers using .ss or !log to corrupt after changing their name?

**Comment by iabarca** [comment]
Can you reproduce this with a particular demo every time? In that case can you upload it somewhere please.

And by corrupt you mean you can't view them? That's weird.

**Comment by Bearnaut** [comment]
Hello, sorry for the delayed response.
I'm somewhat familiar with this bug where you try to play a demo but then you get a message on the console saying "uknown command demopauseafterinit" which according to what I searched could be fixed by deleting all VDM files in my tf folder, if that didn't fix it then the demo would remain unwatchable, hence, corrupted (which was my case). I tried many different demos and I got that message over and over, both through the console and DemoUI and DemoUI2, something that happened after I added a number to the end of the demo as a way for me to sort them as I reviewed them and caused me to lose 60 demos (</3).
That happened to the demos that already were in my hard drive, as I adcquired more through more gameplay, the crash after selecting "load" started happening but the console worked just fine, and also the demoui worked alright after loading from the console but god forbid you from trying to load from the ui.
Here's a couple demos I experienced problems with after labeling them
http://www.mediafire.com/download/m830qsh7iqx3rur/20150302_2107_cp_sunshine_rc5_pipes_pissas+9.dem
http://www.mediafire.com/download/79svjlp4v7fk5ni/20150116_1939_cp_snakewater_final1_jonas_blu+60.dem

**Comment by iabarca** [comment]
"Demos don't work if they have spaces in their names and you load them with demoui. This is also true for folder names."

http://teamfortress.tv/thread/19131/demo-problem/?page=1

This doesn't appear to be linked to Lawena. Closing this - people can still comment.
