### ISSUE TITLE
Pixelfog

### ISSUE THREAD

**Issue by Kaneco** [iabarca/lawena-recording-tool#59]
When I launched lawena after the newest update I noticed the game was very foggy, which wasn't normal. After coming here, I noticed u added the pixelfog thingy, but shouldn't the fog disappear when u have "Disable Pixelfog" selected? Because for me it's behaving the opposite way, I have "Disable Pixelfog" deselected to disable the fog.

**Comment by iabarca** [comment]
Yeah I mixed them up and patched it. Thanks
