### ISSUE TITLE
How was removing the voice command menu done?

### ISSUE THREAD

**Issue by DannyJS1** [iabarca/lawena-recording-tool#60]
An issue I've been having with demo playback is that the voice command menu and taunt selection menus linger after a voice command/taunt is used during the playback. I've solved the taunt issue by unequipping the taunts before playing the demo, but I've never figured out how to remove the voice command menu that appears when you press z, x, or c. When I tried this tool out, I saw that the voice menu was completely gone during a demo playback. How did you disable it? How can I disable it myself without using the tool?

**Comment by iabarca** [comment]
It's done by disabling the command aliasing it with an empty string.

```
alias voice_menu_1 ""
alias voice_menu_2 ""
alias voice_menu_3 ""
```

**Comment by DannyJS1** [comment]
Thanks, that worked! I just wish there was a different way of disabling the taunt selection menu instead of having to unequip them. alias taunt "" doesn't work.

**Comment by iabarca** [comment]
try ``alias +context_action ""`` and ``alias +taunt ""``

The + is important

**Comment by DannyJS1** [comment]
Dude, thanks a lot! You have no idea how frustrated I've been with this. That's all I needed to ask, I'll just close the issue now. Thanks again!
