### ISSUE TITLE
Lawena Recording Tool will not open at all. 

### ISSUE THREAD

**Issue by FrankLockes** [iabarca/lawena-recording-tool#63]
I have tried all troubleshooting issues, tried different versions of java, redownloaded the tool, and downloading different versions of the tool. It will just not work, please help.

**Comment by iabarca** [comment]
I need more information to help you. What happens when you double click the lawena.exe file? Any window popup or error message?

Please submit the files ``launcher.log`` and ``lawena.0.0.log`` if exists to http://pastebin.com/

**Comment by FrankLockes** [comment]
When I open the lawena.exe the picture that looks like this   http://prntscr.com/7cbkuc    comes up but it never opens, no, I have not gotten any popups or error messages.

I could only find the launcher.log here it is: http://pastebin.com/fMXnyEdX

**Comment by iabarca** [comment]
Frank, your issue is caused by the "!" character in your folder structure. The launcher (which is a separate application bundled into the tool) is complaining about that.

```If the full path to the app directory contains the '!' character, this will trigger this error.'.```

Please extract Lawena to another folder. That should fix it.

**Comment by FrankLockes** [comment]
Thank You So Much! It works just as it had when it used to work for me! I appreciate helpful people like you! :D

**Comment by iabarca** [comment]
You're welcome, glad to know it's working.
