### ISSUE TITLE
Spy revolver animation

### ISSUE THREAD

**Issue by 92Ber** [iabarca/lawena-recording-tool#65]
After the latest Gun Mettle Update I am having a problem with every Spy's revolver animation. It twitches during shooting using lawena. Is it just me or the update messed something up?

Here you can see it: https://youtu.be/KOipw3UCv04?t=2m8s

**Comment by iabarca** [comment]
Could this be related to the autoreload bug? Try turning it off from advanced options while your demo is playing.

**Comment by 92Ber** [comment]
Normally I have it turned off, does lawena turn it on?

**Comment by iabarca** [comment]
Lawena shouldn't change that setting but I've noticed that on my local install it's set to "1" on start.

I might add something to force it to be 0 if it's caused by this. Let me know if turning it off during playback fixes the twitches.

**Comment by iabarca** [comment]
Saw your edit, looks like that bug but now I'm not sure if it's caused by ``cl_autoreload 0`` or ``cl_autoreload 1``

**Comment by 92Ber** [comment]
It indeed was turned on. Turning it off fixed the problem. Thanks for your help!

**Comment by iabarca** [comment]
Great. Thanks to you for reporting it, I'll add something to ensure it stays off.
