### ISSUE TITLE
Videos Not Recording

### ISSUE THREAD

**Issue by BernzMaster** [iabarca/lawena-recording-tool#66]
So when I loaded up my demo and went to the relevant tick I hit 'p' to start recording and nothing happened. I opened up the console and there was no indication it had started recording, but it did say at the beginning of the logs the list of keybinds so I assume Lawena was working properly, as well as the custom sky was working fine. I cam online to find an answer to the problem and it suggested binding 'p' to 'startrecording' which didn't work so I then manually typed 'startrecording' into the console followed by 'stoprecording' at the relevant point which did yield TGA files and a WAV file, but they covered an incomplete section of what I thought I had actually recorded....

I hope this problem sounds familiar to you because I really want to fix it!
Thanks,
Bernz

**Comment by iabarca** [comment]
My only guess is that you have something else being bound to P key during the demo playback - it recorded every command and bind inputted when it was originally created.

Recording directly with the command seems not ideal, as it starts once you leave the console/menu, so I suggest you manually change the bind from the P key to another one. You would have to edit the file called ``recbindings.cfg`` located in the ``lawena/cfg`` folder. These are the lines:

```
alias startrecording "host_timescale 0.001; snd_soundmixer Default_Mix; recframerate; bind P stoprecording; namescroll"
alias stoprecording "endmovie; host_timescale 1; host_framerate 0; bind P startrecording"

(...)

bind P startrecording
```

And modify the 3 "P" instances accordingly. Downside to this method is that after every update that file might be returned to its default state.

**Comment by BernzMaster** [comment]
I tried this method separately for 'o' and for '[' but neither keys worked.
After changing the 3 keybinds in recbindings.cfg, INCLUDING the third one it still didn't stop/start and when sing the 'showhelp' command in the console it still said that the bind was 'P'.

Originally I had team chat bound to 'p' but I changed it to 'o' when I first tried to use Lawena, but this still didn't work.

**Comment by iabarca** [comment]
The showhelp command contents come from a .cfg file so it does not keep track of the actual key if you changed it. Make sure you edited the key before you launch the game and once you launch it confirm that it's there in your ``tf/cfg`` folder.

**Comment by iabarca** [comment]
@BernzMaster if you have any followup to this I'd appreciate it. This issue is common but the provided fix should have done it so the fact that it didn't for you intrigued me.
