### ISSUE TITLE
Restoration of directories does not work if they are symlinks

### ISSUE THREAD

**Issue by PazerOP** [iabarca/lawena-recording-tool#67]
If your custom directory (and I'm assuming your cfg directory too) are symlinks (created with the mklink program, part of windows), they will not be restored when you close tf2/lawena. Instead, they will be replaced with properly-named empty folders that are not symlinks. When lawena originally backs up your files it behaves properly, renaming the symlinks to lwncustom and lwncfg, but the issue seems to only occur with restoration.

This is important for me because I have TF2 installed on an SSD without much space. Moving large directories to other drives helps keep the size of my TF2 installation down.

**Comment by iabarca** [comment]
Hi, thanks for bringing this to my attention. Would you help me to test the fix I deployed?

You need to switch to the "preview" branch from the Help > About menu item, then press "Select Updater Branch" and select the "preview-v4.1" option. Then press OK and restart Lawena. Once the tool reopens, version at the top must say "4.1.8-9". Let me know if it's working.

**Comment by PazerOP** [comment]
Works for me. Thanks for the ultra-fast response and fix!
