### ISSUE TITLE
Start TF2 directly instead of through Steam

### ISSUE THREAD

**Issue by PazerOP** [iabarca/lawena-recording-tool#68]
The following is a suggestion to fix what is causing the following issue: when launching TF2 through lawena, the command line contains both the arguments from lawena's "Custom Launch Options" window AND the arguments from Steam's "Set Launch Options" window.

![Image of command line of hl2.exe](http://pazer.us/screenshots/puush/ss%20(2015-09-26%20at%2009.43.33).png)

If the game is launched directly through the exe and not through Steam, this does not happen and you will only get the command line arguments you actually want (that you specified in lawena).

Main issue here is I want +mat_dxlevel 81 on my Steam command line, but I want +mat_dxlevel 95 on my lawena command line.

**Comment by iabarca** [comment]
I had no idea it combined parameters like that. I expected more from Valve :disappointed: 

Looks like the minimal set of parameters is ``-steam -game tf``.

**Comment by iabarca** [comment]
Pushed to preview branch. Older behavior is now located at the "Advanced menu > Launch using Steam" menu item.
