### ISSUE TITLE
Lawena adds additional dxlevel to command line

### ISSUE THREAD

**Issue by PazerOP** [iabarca/lawena-recording-tool#69]
If I specify +mat_dxlevel on Lawena's "Custom Launch Options" window, I'd like it if Lawena didn't also add -dxlevel to the command line automatically. The label on the Custom Launch Options window explains that DxLevel will be automatically added to the command line if it is not present, but this is only true if you specify -dxlevel there, not +mat_dxlevel.

I want to use +mat_dxlevel 95 instead of -dxlevel 95 because +mat_dxlevel simply changes the target dxlevel rather than instructing the game to throw away your entire graphical config.

**Comment by iabarca** [comment]
https://developer.valvesoftware.com/wiki/Mat_dxlevel

> This can also be specified with Launch Options, use +mat_dxlevel [DirectX version] on the launch options of any Source game to do so. Alternatively, you can use -dxlevel [DirectX version], however this specifies a number of extra presets, including resolution and quality.

It would be good to know what extra presets are set to see if in the future ``+mat_dxlevel`` can be set instead of ``-dxlevel``.

I'll add something to avoid having both on the command line.

**Comment by PazerOP** [comment]
Updated the wiki with the presets that I could find that were changed by -dxlevel: https://developer.valvesoftware.com/wiki/Mat_dxlevel
