### ISSUE TITLE
Weapon Jitter

### ISSUE THREAD

**Issue by FrankLockes** [iabarca/lawena-recording-tool#70]
I opened my demo and was looking at the jump I did, during the time i was not shooting, the player weapons would start jittering rapidly. Is there any way to fix this? I haven't found 1 article on the internet about this.

**Comment by iabarca** [comment]
I'm guessing it's related to auto reload. Can you type the following command into the console:

``alias cl_autoreload ""``

Let me know if it works, to add it by default to the config.

**Comment by iabarca** [comment]
Also noting that this might be the same case as #65 so you should also set the value to 0 before locking it. Type ``cl_autoreload 0`` before the alias command.

**Comment by FrankLockes** [comment]
The command you have presented to me works, but it brings a whole new problem. It makes the rocket launcher shooting animation go away. Here is what I mean: https://www.youtube.com/watch?v=JpG2XREModA&feature=youtu.be Any Ideas?

**Comment by iabarca** [comment]
I've never seen that before. No idea why, maybe there's another active command we're not aware of?

Let us know if you find a pattern in case it happens to you again, for example if this happens only on very old demos, only with soldier + rocket launcher, only with that autoreload 0, etc. Anything that helps to reproduce the problem.

You could also upload the .dem file to see if it happens to other people as well.

**Comment by FrankLockes** [comment]
Okay I will upload the demo later, thanks for the advice.
