### ISSUE TITLE
Strange visual errors

### ISSUE THREAD

**Issue by DomoCatFace** [iabarca/lawena-recording-tool#71]
I was trying to record some footage using Lawena and I came across some weird errors. Green uber and fire flashes? The fire flashes seem to correlate with explosions that happen on the map. I am using a different config other than chris' max quality, not sure if it has anything to do with it.
Video: https://www.youtube.com/watch?v=UPViXO7L4Cs&feature=youtu.be

**Comment by iabarca** [comment]
Can you attach the config? And are you replacing one of lawena configs or using it as a "custom" file?

**Comment by DomoCatFace** [comment]
I tried r_queued_post_processing 0, did not work
I put this - https://dl.dropboxusercontent.com/u/92187841/stability.cfg into recording.cfg and removed Chris' max frames, i like the look of my config when making videos

**Comment by iabarca** [comment]
Too many differences between configs, I wouldn't know where to start to check which one is causing these.

Are you sure it happens only when using Lawena? If that's the case, could you upload a demo to see if it can be replicated across machines.

**Comment by DomoCatFace** [comment]
Sure
Here's the config I am using straight out of lawena/cfg : http://www.filedropper.com/recording
And
Demo I showed in the video : http://www.filedropper.com/201510081912cpsnakewaterfinal1redblu
