### ISSUE TITLE
Allow resizing of the "Custom Settings" window

### ISSUE THREAD

**Issue by PazerOP** [iabarca/lawena-recording-tool#72]
Would be great if we could resize this window (and have the textbox within it resize as well). Right now I've got only about 50 lines of text in there, but it feels so much more cramped because the window is so small and not resizable.
http://puu.sh/lGOyn/58f8729dfb.png

**Comment by iabarca** [comment]
Thanks for the feedback, I've updated the preview branch (version 4.1.9-4) with this implemented.

It should remember your settings and the dialog size.
