### ISSUE TITLE
Lawena deleted my custom files

### ISSUE THREAD

**Issue by code-al** [iabarca/lawena-recording-tool#73]
I used lawena for quite a while now but just now it suddenly deleted all my files in my custom folder. I think it might have been because I unticked a custom resource before I exited TF2 which probably caused it to malfunction? Anyway I don't want to edit my custom hud again... is there anyway to get my files back? I can't find the lwrt folders in my tf folder and lawena folder. Please help...

**Comment by iabarca** [comment]
First of all, sorry for the inconvenience. Can you check if you have the zipped backups in your tf folder? They are named lawena-user.*timestamp*.bak.zip

Then I would like to able to reproduce this, can you submit a log file (lawena.0.0.log) to check for details? Upload it to pastebin or here if you change the extension of that file to .txt

**Comment by code-al** [comment]
Yes there is! And I found my hud! Thanks! Here's the log file anyway
http://pastebin.com/YzJ3xFBu

**Comment by iabarca** [comment]
Glad to know about the backup. This seems like a bug so thanks for reporting it.

**Comment by iabarca** [comment]
For now we will have to work around this issue by requiring only 1 instance of Lawena open at a time and having backups always enabled by default while I make some time to build a more robust solution.
