### ISSUE TITLE
Taunting not working

### ISSUE THREAD

**Issue by Ninjatattie** [iabarca/lawena-recording-tool#74]
I installed Lawena tool for tf2 but then didn't want it so i deleated all the lawena files in the tf folder but now i can't taunt and i think it is lawena because in the console it says it is looking for the recording.cfg and i thought i unistalled it. Please help

**Comment by iabarca** [comment]
Can you check for lwrtcfg and lwrtcustom folders inside your tf folder?. Those have your files.

**Comment by Ninjatattie** [comment]
i deleted those files when i was trying to get rid of it

**Comment by iabarca** [comment]
Lawena swaps your cfg/custom folders with lwrtcfg/lwrtcustom. If you got an error then you should have a zip file in your tf folder named "lawena-user.(timestamp).bak.zip".

**Comment by Ninjatattie** [comment]
no i don't have that because i reinstalled tf2
are you sure that lawena dosen't put files anywere else?

**Comment by iabarca** [comment]
No, sorry. It moves your files to lwrt* folders and zips them in case an error happens, but if you deleted all those files then I can't help you there. To get default cfgs you should delete cfg and revalidate game.

**Comment by Ninjatattie** [comment]
and if i get the default cfgs then will it fix my taunts because it's not the binds i'm quite sure

**Comment by iabarca** [comment]
Yeah you most likely have a config.cfg which saved all previous Lawena cfgs, including the aliases that disable taunting and the keybinds. Going back to defaults will fix that.

**Comment by Ninjatattie** [comment]
this is what it says in my settings.exec

alias recframerate host_framerate 60
alias currentfpsup 120fps
alias currentfpsdn 3840fps
mat_motion_blur_enabled 1
mat_motion_blur_forward_enabled 1
mat_motion_blur_strength 1
cl_cloud_settings 0
con_timestamp 1
viewmodel_fov 90
cl_crosshair_file ""
cl_crosshair_red 200
cl_crosshair_green 200
cl_crosshair_blue 200
cl_crosshair_scale 32
cl_crosshairalpha 200
crosshair 0
hud_combattext 1
hud_combattext_healing 1
tf_dingalingaling 0
voice_enable 0
alias voice_enable ""
cl_autorezoom 1
cl_autoreload 1
hud_saytext_time 0
net_graph 0
alias net_graph ""
alias voice_menu_1 ""
alias voice_menu_2 ""
alias voice_menu_3 ""
alias +taunt ""
alias +context_action ""
cl_showfps 0
alias cl_showfps ""
volume 0.5
hud_fastswitch 1
cl_hud_minmode 0
cl_hud_playerclass_playermodel_showed_confirm_dialog 1
cl_hud_playerclass_use_playermodel 0
engine_no_focus_sleep 0
cl_spec_carrieditems 0
tf_hud_target_id_disable_floating_health 0
// Custom User Settings
lockviewmodelson
//lockviewmodelsoff
lockcrosshair
alias toggle ""

but the main thing is the +taunt, do you know what to do with that?

**Comment by Ninjatattie** [comment]
that might be what is causing the problem

**Comment by Ninjatattie** [comment]
it's working now I just deleated the autoexec file and it works so thank you for your time

**Comment by iabarca** [comment]
Glad you could sort it out
