### ISSUE TITLE
Player models are frozen in a corner of the map

### ISSUE THREAD

**Issue by nobelharvards** [iabarca/lawena-recording-tool#75]
I suspect igmdb.org also uses Lawena, because when I submit a demo to them, the same problem happens.

https://youtu.be/DoB-Rso0fw0

This is what I have tried.

Launching TF2 NOT through Lawena, default TF2 settings on -dxlevel 81 and -dxlevel 98. Both play the demo with no problems.

In Lawena, I have tried commenting out each of the 3 lines for execing the other configs in the autoexec, one at a time. No effect. Problem depicted in video still present.

I tried reverting Lawena settings all to default. No effect. Problem depicted in video still present.

I have tried deleting Lawena and downloading a fresh copy. No effect. Problem depicted in video still present.

Sorry if this is a well documented issue. I am not sure what to search in Google.

**Comment by iabarca** [comment]
Seems like a TF2 issue with the demo playback, triggered by one of the settings in the config + something in the demo file.

To confirm this you can try launching Lawena with default settings, In Advanced > Custom launch options menu, add ``-default``. This will block every cvar in the recording.cfg and settings.cfg files.

If the above does not show the problem then one of the cvars in the settings.cfg file is triggering this, since when you commented out those autoexec.cfg lines you are not entirely skipping it because the file is executed on demo start and on every class change.

These experiments can help to then submit a report to Eric Smith.

**Comment by nobelharvards** [comment]
Adding -default to Lawena's launch options no longer shows the problem.

This is a dump of settings.cfg. It is mostly default with hitsound settings added in.

alias recframerate host_framerate 60
alias currentfpsup 120fps
alias currentfpsdn 3840fps
mat_motion_blur_enabled 0
mat_motion_blur_forward_enabled 0
mat_motion_blur_strength 0
cl_cloud_settings 0
con_timestamp 1
viewmodel_fov_demo 74
cl_crosshair_file ""
cl_crosshair_red 200
cl_crosshair_green 200
cl_crosshair_blue 200
cl_crosshair_scale 32
cl_crosshairalpha 200
crosshair 1
hud_combattext 0
hud_combattext_healing 0
tf_dingalingaling 0
voice_enable 0
alias voice_enable ""
cl_autorezoom 0
cl_autoreload 0
hud_saytext_time 0
net_graph 0
alias net_graph ""
alias voice_menu_1 ""
alias voice_menu_2 ""
alias voice_menu_3 ""
alias +taunt ""
alias +context_action ""
cl_showfps 0
alias cl_showfps ""
volume 0.5
hud_fastswitch 1
cl_hud_minmode 1
cl_hud_playerclass_playermodel_showed_confirm_dialog 1
cl_hud_playerclass_use_playermodel 0
engine_no_focus_sleep 0
cl_spec_carrieditems 0
tf_hud_target_id_disable_floating_health 1

// Custom User Settings
volume 1

// Hitsound
tf_dingaling_pitchmaxdmg 65
tf_dingaling_pitchmindmg 135
tf_dingaling_volume 1
tf_dingalingaling 1
tf_dingalingaling_repeat_delay 0

hud_combattext_doesnt_block_overhead_text 1

tf_hud_no_crosshair_on_scope_zoom 1

lockviewmodelson
//lockviewmodelsoff
lockcrosshair
alias toggle ""

**Comment by nobelharvards** [comment]
I have solved the issue. The fault is mine.

I had "exec autoexec" in every class config. Apparently that behaviour is saved into the demo file, so it does not matter if Lawena copies over its own cfgs.

The result is, playing demos in TF2 with my regular setup is fine, but using Lawena to play demos results in the bug shown in the video in the earlier reply.

I have "exec autoexec" in every class config because there are some commands that reset at every map change, therefore putting them in autoexec is redundant.

I have not narrowed down every cvar that changes on map change, but I know these 4 do, so I've replaced "exec autoexec" with a classcommon.cfg with these 4 commands in it:

cl_detaildist 0
cl_detailfade 0
r_cheapwaterend 1
r_cheapwaterstart 1

Sorry for any headaches I caused you.

**Comment by iabarca** [comment]
Thanks for leaving a reply explaining the situation. Lawena "works" as long as it can disable/block all those commands that get recorded into every demo file.
I'm not sure yet how to block "exec autoexec" lines without messing with the cfg files while TF2 is running, so this issue can help in case someone else has a similar class config setup.
