### ISSUE TITLE
"Disable Hitsounds" doesn't disable the new killsounds

### ISSUE THREAD

**Issue by PazerOP** [iabarca/lawena-recording-tool#79]
I think it is implied that disable hitsounds should disable all added audio feedback for hitting/killing someone. This setting should also set tf_dingalingaling_lasthit to 0.

**Comment by iabarca** [comment]
Hitsounds refers to the 'dingalings', right now configured only using cvars. I will add that line to the config.

Are there additional sounds you think should be disabled? I can make a separate blank audio VPK for that if you let me know which sounds not covered by `tf_dingalingaling*` settings should be disabled.

**Comment by iabarca** [comment]
Latest preview version contains the cvar. I'll wait for your reply to see if there are more to this before closing and pushing an update to stable version.

**Comment by iabarca** [comment]
Fixed in v4.1.11
