### ISSUE TITLE
[Feature Request] Batch Recording HLAE Smooths

### ISSUE THREAD

**Issue by JCBrouwer** [iabarca/lawena-recording-tool#83]
Hi, I'm trying to record a lot of HLAE smooths using the VDM tab but there is currently no way to add the camera import commands (that I can find anyway). I've found a work around but it's a bit tedious and I'm wondering if it could be added to the VDM tab natively.

It basically comes down to just adding the HLAE import commands to the generated VDM files, but there's one hitch. The mirv_camimport command requires the full path to the BVH files as a parameter. This is a problem because VDM files don't play nicely with the extra quotation marks around the path, so each smooth you want to import needs an individual CFG file containing the full mirv_camimport command. Once you've got the CFG all you need to do is add an exec before the startrecord command in each VDM file.

The batch recording works perfectly if you follow the above process, but I'd rather have Lawena doing the prep work for me instead of having to manually create a bunch of one line CFG files. Maybe this has already been implemented in the new v5 VDM editor but if not I think it could improve a lot of people's workflow!

**Comment by iabarca** [comment]
It is certainly possible. Can you send me an example of the resulting VDM file you would like to have?

**Comment by JCBrouwer** [comment]
[Here's](https://github.com/iabarca/lawena-recording-tool/files/374814/examle.zip) some example files. If you drag them all into your tf folder you should be able to try it out with Lawena by just playing the demo (you'll need to change the path in the CFG file to your own tf folder).

The BVH file was made by exporting the demo with HLAE and recording the smooth in an external program. The VDM file is basically exactly the same as the one Lawena generated but with "exec metalworks" added before startrecording which executes the CFG file that imports the smooth.

**Comment by iabarca** [comment]
I'm going to add support to this but I'm not sure if commands other than
`mirv_camimport` are going to be needed, for other cases. Just seeing if it's worth to make that configurable, at least on the initial release.

For now, this is my to-do list:

- [ ] Include a separate "Add exec+record" button in the VDM tab
- [ ] Generate the `"exec config; startrecording"` line in the resulting VDM file
- [ ] Auto-generate a CFG file following a template like `mirv_camimport start {{BVH full path}}`

If you notice something missing let me know. Thanks for suggesting this feature :smiley:

**Comment by iabarca** [comment]
I've deployed an initial implementation of this to the preview branch. To access this you must go to the Help -> About menu item. Then Select Updater Branch and choose **preview-v4.1**. 

Can you check it out and tell me if it works fine?

**Comment by JCBrouwer** [comment]
Wow that was fast!

I just tried it out and it couldn't find the CFG file that was generated because it was in the tf folder. I think TF2 can only see CFGs located in tf/cfg or tf/custom.

Also I've noticed that clicking "Delete VDM Files" only deletes VDMs in the tf folder. I keep most of my demos in the new tf/demos folder and, while Lawena does manage to create the VDMs there correctly, it doesn't delete them.

(Sidenote: the main menu looks pretty sweet, but I couldn't select the top 3 options of the dropdown because it said I wasn't connected to the game coordinator)

**Comment by quanticc** [comment]
Okay, thanks for the feedback, pushed some updates:
- The CFG files will be generated in the Lawena `cfg` folder, so they will be copied to your TF dir when launching. I think that's the correct place? Because they can be created on tf/cfg but it would require that the game was already launched.
- The Delete VDM button will also include the folder of the current selected demo. I can't make a broader scan without requiring a folder from the user.
- ~~I've reverted the main menu HUD update, contacted the maker to see if a fix is possible.~~ HUDs fixed.
