### ISSUE TITLE
Failed to replace hud files.

### ISSUE THREAD

**Issue by maxijabase** [iabarca/lawena-recording-tool#84]
I started having this issue some time ago, my fix was delete lawena executable and foler, extract it again, let the Java thing run again, but now it doesn't work at all. Yesterday it was working and I made a video with it, but today I Can't seem to make it work. I need help, please! I'm not using any custom huds or modifications to it and I have already updated Java to 101 and then restarted my PC.

**Comment by ratawar** [comment]
[http://i.imgur.com/sCHgc2I.png](url)

**Comment by maxijabase** [comment]
http://i.imgur.com/sCHgc2I.png

**Comment by quanticc** [comment]
Can you send me the lawena.0.0.log file located in the lawena folder? If you rename the file to TXT you can attach it to a commentary here on GitHub, otherwise use http://hastebin.com/

**Comment by quanticc** [comment]
Also it is likely that you have remnants of a previous Lawena launch. Lawena uses the lwrtcfg and lwrtcustom folders to store YOUR files while the game runs with Lawena.

If those folders exist the launch will be aborted. Don't delete them manually though without backing up your own files though, they are located in lwrtcfg and lwrtcustom folders.

**Comment by maxijabase** [comment]
[lawena.0.0.txt](https://github.com/iabarca/lawena-recording-tool/files/380042/lawena.0.0.txt)

**Comment by quanticc** [comment]
Ok it's a bug. Try to use a custom or killnotices hud for now. Going to fix
this during the day.

Thanks for reporting it!

**Comment by quanticc** [comment]
Fix is available in preview branch, update to stable will be made soon.

To access the preview branch you must go to the `Help -> About` menu item. Then Select Updater Branch and choose **preview-v4.1**.

Update: Fix is now available on v4.1.14 stable also

**Comment by maxijabase** [comment]
No problem, thank you for your hard work on such a useful tool :)
