### ISSUE TITLE
Chat box opening

### ISSUE THREAD

**Issue by itslemons** [iabarca/lawena-recording-tool#85]
Hi, I've started recording a few clips, and the chat box is always open. I've turned off all visible and enable options in Basechat.res, and have tried using hud_saytext_time 0 when I record, all to no avail. Any idea how to get rid of the chat?

Thanks

**Comment by quanticc** [comment]
I don't think this is a Lawena issue. Are you sure it happens only when using Lawena?

If you attach the zipped demo to a comment I can check if it's some keypress or command being executed as the demo plays.
