### ISSUE TITLE
Lawena won't start, asks for JRE even though I already have it

### ISSUE THREAD

**Issue by maxijabase** [iabarca/lawena-recording-tool#87]
Hey, it's me again. Now I downloaded latest v4.1.1.4 and it won't even start, it pops this out:
http://i.imgur.com/OEq2uLo.png
I checked the name of the file it tries to download, and I downloaded latest x64 JRE, which is 8u101, then rebooted, still same. Am I doing something wrong?

**Comment by maxijabase** [comment]
I don't have any log file because it won't even start to generate one.

**Comment by quanticc** [comment]
This is an issue with the program I use to build the .exe - Releasing a fix soon.

**Comment by quanticc** [comment]
Fixed in new release: https://github.com/iabarca/lawena-recording-tool/releases/tag/4.1.15

Alternatively, added a working **lawena.exe** here: https://github.com/iabarca/lawena-recording-tool/releases/download/4.1.14/lawena.exe
