### ISSUE TITLE
TF2 Crashing when it attempts to load a demo from another demo (from VDM files)

### ISSUE THREAD

**Issue by ghost** [iabarca/lawena-recording-tool#88]
The title says it all. 
So after two times attempting to render with the queue, I've noticed that TF2 seems to crash whenever it should load a different demo, after the first demo in the queue finishes rendering.
My settings for both Lawena, and SrcDemo2 are in the included image.
![image](https://cloud.githubusercontent.com/assets/21959771/18220844/ee882efe-7143-11e6-89ef-a334513d69cf.png)
![image](https://cloud.githubusercontent.com/assets/21959771/18220866/2d55fd14-7144-11e6-9200-f18ed89384c1.png)

The only custom settings i have is mat_phong 0.

**Comment by quanticc** [comment]
Does it happen with any kind of two demos? I will try to reproduce the problem soon.

**Comment by ghost** [comment]
As far as i know yes. On both of my attempts to batch render, it crashed after the first demo went to go play the second demo.

**Comment by quanticc** [comment]
Thinking it might be a TF2/Source engine issue for now, hoping to find a way to mitigate the crash

**Comment by ToxicIMP115** [comment]
Did it happen for you too?

**Comment by ghost** [comment]
Hm. The only thing i can think of to temporarily fix this is kinda dumb. Basically, have TF2 quit after every demo, but edit the autoexec after every tf2 close (besides the final one), to make it play the next demo in queue after about five minutes or so (to ensure tf2 loads up properly). The thing is i have no idea if it would cause issues with srcDemo2 or not.

**Comment by ghost** [comment]
Scratch that, I had an idea that might work, I haven't tested yet though. Basically, have a demo execute a confg file that contains the following commands

disconnect
// stops the demo 
wait 11880
// Wait goes on frames (according to the wiki), and 66 frames is about a second,
// 66 x 60 is 3960 frames a minute, multiplied by three for three minutes it is
// 11880
playdemo nextdemoname

I'll test it then get back to you.
So far it fails to delay playing the next demo when it is on the menu screen.
It might even work without the wait command, I'll have to test it .

**Comment by ghost** [comment]
I tested it, it didn't work unfortunately. So maybe it is a source engine bug, or maybe my computer is just that bad :P
