### ISSUE TITLE
Unable to launch at all

### ISSUE THREAD

**Issue by lrodell** [iabarca/lawena-recording-tool#94]
Recieve this message on startup: http://i.imgur.com/FVNHclv.png?1

**Comment by quanticc** [comment]
Thanks for bringing this up to me, It's related to the Dropbox public folder stopping its functions.

Can you use this launcher for now: https://github.com/quanticc/lawena-recording-tool/releases/download/4.1.15/lawena-launcher-skip-updater.zip

**Comment by TREVTRPD** [comment]
@quanticc Im also unable to launch, the launcher doesnt help ;-;

**Comment by quanticc** [comment]
Alright, released a new version with this fixed. I can't provide a clean update path for v4.1.15 so you must download the new zip from the releases page:

https://github.com/quanticc/lawena-recording-tool/releases/tag/4.1.16

Sorry for the troubles.

**Comment by TREVTRPD** [comment]
@quanticc Thank you for your effort :)

**Comment by lrodell** [comment]
@quanticc thank you! :)

**Comment by basicwhiteboy** [comment]
well, the installer finished. now what? either something is going on behind the scenes, or it's not working.
