### ISSUE TITLE
Custom Skyboxes not appearing in Lawena

### ISSUE THREAD

**Issue by eddie-englund** [iabarca/lawena-recording-tool#95]
I've added several custom skyboxes. I made one for a greenscreen, but they are not appearing in lawena.
![capture](https://cloud.githubusercontent.com/assets/16852656/24841753/7e684bfa-1d8b-11e7-8afd-9f7d192292a6.PNG)

**Comment by quanticc** [comment]
You should have a file called greenscreen**up**.vtf. That's the important one.

Also greenscreenup.png for the preview icon. Lawena uses that nomenclature (up/dn/ft/bk/lf/rt) to map each section of the skybox.
