### ISSUE TITLE
Game runs at 20 FPS after Lawena

### ISSUE THREAD

**Issue by TheRealGDEabarod** [iabarca/lawena-recording-tool#97]
Before I used Lawena, I had about 60-100 fps, but after using lawena, its at 20
I used lawena, but before it could shut down properly, it crashed.
I think is screwed up some of my settings, but after using custom frames configs, it still has not gone up

**Comment by quanticc** [comment]
There's probably remnants of the lawena config files in your game. Check if you have lawena files in your cfg folder. You can also check if you have folders like "lwrtcfg" and "lwrtcustom" which means your files could also be there.

Remember to always have backups of your config files!

Normally when you close the application, it resets your files back. But it could happen that they remain there, in those cases you can manually restore your config.

**Comment by TheRealGDEabarod** [comment]
i got rid of all the files but it still runs at low fps

**Comment by quanticc** [comment]
Can you check if you have zip files called "lawena" and a timestamp in your tf folder? Because if you don't have a backup of your own config to restore your settings back, it could be there.

Otherwise you'll have to reset to defaults with -autoconfig and work from there.

**Comment by TheRealGDEabarod** [comment]
how can you reset using -autoconfig?

**Comment by TheRealGDEabarod** [comment]
i tried to reset it, but it didn't fix anything...

**Comment by TheRealGDEabarod** [comment]
Okay, so I used a fps config that makes my game look like crap, but my frames aren't going up. Maybe there is a command that controls frames rather than graphics

**Comment by quanticc** [comment]
Lawena uses a config to push graphical settings to the maximum, so maybe there's a config value that you haven't reset.

Can you send me your config.cfg file to determine which setting could be causing it?

**Comment by TheRealGDEabarod** [comment]
[config.zip](https://github.com/quanticc/lawena-recording-tool/files/1150492/config.zip)

**Comment by quanticc** [comment]
Take a look at these configs http://www.teamfortress.tv/25328/comanglias-config-fps-guide

You don't seem to have any particular movie making setting set in the config, so those values were probably saved and stuck with your game.

Instead of trying to revert each one of them, [going back to defaults](https://www.reddit.com/r/truetf2/comments/2frkym/how_do_i_reset_my_tf2_to_fully_default/) and **then** copying your config.cfg file over the defaults should make the trick.

**Comment by TheRealGDEabarod** [comment]
Didn't work :(

**Comment by TheRealGDEabarod** [comment]
I've tried reinstalling, verifying game files, restarting with -autoconfig, deleting my configs

**Comment by quanticc** [comment]
Have you tried using a different dxlevel, Lawena sets -dxlevel 98 by default but normally we use a much lower than that to play (81, 90)

**Comment by TheRealGDEabarod** [comment]
Yeah, I set dxlevel 81 in my launch options

**Comment by TheRealGDEabarod** [comment]
Okay, I think what is happening is that when I put autoconfig and default in the launch options, it goes to default, fixing my problem, but causing low fps because I can't set other values low. When I take them out, it execs the saved values.

**Comment by TheRealGDEabarod** [comment]
I think I fixed the problem, but another one has come up
