### ISSUE TITLE
Lawena messing up my Laptop (maybe)

### ISSUE THREAD

**Issue by TheRealGDEabarod** [iabarca/lawena-recording-tool#98]
Whenever I play another game, whether it be Overwatch, or CoD4, or Dirty Bomb, my FPS has gone down significantly, from 30 fps to 5, or 80 fps to 10
Does Lawena mess with my graphics card or my Laptop?

**Comment by quanticc** [comment]
No, check temperatures and GPU profiles

**Comment by TheRealGDEabarod** [comment]
Okay

**Comment by TheRealGDEabarod** [comment]
Lol, I just needed to plug my laptop into another wall
