### ISSUE TITLE
Lawena doesnt open

### ISSUE THREAD

**Issue by Smoothie123** [iabarca/lawena-recording-tool#99]
When im trying to launch lawena its says : "this application has failed to launch due to a missing resource
https://dl.dropboxusercontent.com/u/74380/lwrt/v4.1.x/stable/lastest/getdown.txt"

**Comment by quanticc** [comment]
Get the latest version, that link is dead and we're using a new service now.

https://github.com/quanticc/lawena-recording-tool/releases/latest

**Comment by SykoMemes** [comment]
I have the same issue however, I have the latest version of Lawena
